# Generated by Django 5.2.1 on 2025-06-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Категории товаров',
            },
        ),
    ]
